// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1IG2oZdEAmCltIfIhlrM4VI0_f2yWqs',
    appId: '1:676733745534:web:c773be23e499f423fc5b2f',
    messagingSenderId: '676733745534',
    projectId: 'noteassist-9dd81',
    authDomain: 'noteassist-9dd81.firebaseapp.com',
    storageBucket: 'noteassist-9dd81.firebasestorage.app',
    measurementId: 'G-LT98KN9F9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5s-BCHvml_7k-qgBXFxQjB5bafS2O974',
    appId: '1:676733745534:android:a3aefebfb443a5f8fc5b2f',
    messagingSenderId: '676733745534',
    projectId: 'noteassist-9dd81',
    storageBucket: 'noteassist-9dd81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zNcay_kPmawgSLNAWJlu_i7NrxXoOY0',
    appId: '1:676733745534:ios:c745a2e31a5513c7fc5b2f',
    messagingSenderId: '676733745534',
    projectId: 'noteassist-9dd81',
    storageBucket: 'noteassist-9dd81.firebasestorage.app',
    iosBundleId: 'com.example.noteassista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zNcay_kPmawgSLNAWJlu_i7NrxXoOY0',
    appId: '1:676733745534:ios:c745a2e31a5513c7fc5b2f',
    messagingSenderId: '676733745534',
    projectId: 'noteassist-9dd81',
    storageBucket: 'noteassist-9dd81.firebasestorage.app',
    iosBundleId: 'com.example.noteassista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi1IG2oZdEAmCltIfIhlrM4VI0_f2yWqs',
    appId: '1:676733745534:web:28e8b022a99533d6fc5b2f',
    messagingSenderId: '676733745534',
    projectId: 'noteassist-9dd81',
    authDomain: 'noteassist-9dd81.firebaseapp.com',
    storageBucket: 'noteassist-9dd81.firebasestorage.app',
    measurementId: 'G-XB65LVTS8T',
  );
}
