import 'package:flutter/material.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import '../models/folder_model.dart';
import '../services/supabase_service.dart';

/// Dialog for creating a new folder
class CreateFolderDialog extends StatefulWidget {
  /// Parent folder ID (null for root level)
  final String? parentFolderId;

  /// List of all folders to check nesting depth
  final List<FolderModel> allFolders;

  const CreateFolderDialog({
    super.key,
    this.parentFolderId,
    required this.allFolders,
  });

  @override
  State<CreateFolderDialog> createState() => _CreateFolderDialogState();
}

class _CreateFolderDialogState extends State<CreateFolderDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final SupabaseService _supabaseService = SupabaseService.instance;

  Color _selectedColor = Colors.blue;
  bool _isFavorite = false;
  bool _isCreating = false;

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  /// Calculate the depth of a folder in the hierarchy
  int _getFolderDepth(String? folderId) {
    if (folderId == null) return 0;

    int depth = 1;
    String? currentParentId = folderId;

    while (currentParentId != null && depth < 10) {
      // Safety limit
      final parentFolder = widget.allFolders.firstWhere(
        (f) => f.id == currentParentId,
        orElse: () => FolderModel(id: '', name: '', color: ''),
      );

      if (parentFolder.id.isEmpty) break;

      currentParentId = parentFolder.parentId;
      depth++;
    }

    return depth;
  }

  Future<void> _createFolder() async {
    if (!_formKey.currentState!.validate()) return;

    // Check nesting depth (max 5 levels)
    final currentDepth = _getFolderDepth(widget.parentFolderId);
    if (currentDepth >= 5) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Maximum folder nesting depth (5 levels) reached'),
            backgroundColor: Colors.red,
          ),
        );
      }
      return;
    }

    setState(() => _isCreating = true);

    try {
      final folder = FolderModel(
        id: '', // Will be generated by Supabase
        name: _nameController.text.trim(),
        parentId: widget.parentFolderId,
        color: '#${_selectedColor.toARGB32().toRadixString(16).substring(2)}',
        isFavorite: _isFavorite,
      );

      final result = await _supabaseService.createFolder(folder);

      if (mounted) {
        if (result.success) {
          Navigator.of(context).pop(true);
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Folder "${folder.name}" created successfully'),
              backgroundColor: Colors.green,
            ),
          );
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Error creating folder: ${result.error}'),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error creating folder: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isCreating = false);
      }
    }
  }

  void _showColorPicker() {
    showDialog(
      context: context,
      builder:
          (context) => AlertDialog(
            title: const Text('Pick a color'),
            content: SingleChildScrollView(
              child: BlockPicker(
                pickerColor: _selectedColor,
                onColorChanged: (color) {
                  setState(() => _selectedColor = color);
                  Navigator.of(context).pop();
                },
                availableColors: const [
                  Colors.red,
                  Colors.pink,
                  Colors.purple,
                  Colors.deepPurple,
                  Colors.indigo,
                  Colors.blue,
                  Colors.lightBlue,
                  Colors.cyan,
                  Colors.teal,
                  Colors.green,
                  Colors.lightGreen,
                  Colors.lime,
                  Colors.yellow,
                  Colors.amber,
                  Colors.orange,
                  Colors.deepOrange,
                  Colors.brown,
                  Colors.grey,
                  Colors.blueGrey,
                ],
              ),
            ),
          ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Create New Folder'),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Folder name input
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'Folder Name',
                  hintText: 'Enter folder name',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.folder),
                ),
                autofocus: true,
                textCapitalization: TextCapitalization.words,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a folder name';
                  }
                  if (value.trim().length > 50) {
                    return 'Folder name must be 50 characters or less';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 20),

              // Color picker
              const Text(
                'Folder Color',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
              ),
              const SizedBox(height: 8),
              InkWell(
                onTap: _showColorPicker,
                borderRadius: BorderRadius.circular(8),
                child: Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.grey[300]!),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    children: [
                      Container(
                        width: 32,
                        height: 32,
                        decoration: BoxDecoration(
                          color: _selectedColor,
                          borderRadius: BorderRadius.circular(6),
                          border: Border.all(color: Colors.grey[300]!),
                        ),
                      ),
                      const SizedBox(width: 12),
                      const Text('Tap to change color'),
                      const Spacer(),
                      Icon(
                        Icons.arrow_forward_ios,
                        size: 16,
                        color: Colors.grey[600],
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 20),

              // Favorite toggle
              CheckboxListTile(
                value: _isFavorite,
                onChanged: (value) {
                  setState(() => _isFavorite = value ?? false);
                },
                title: const Text('Mark as favorite'),
                subtitle: const Text('Favorite folders appear at the top'),
                contentPadding: EdgeInsets.zero,
                controlAffinity: ListTileControlAffinity.leading,
              ),

              // Parent folder info
              if (widget.parentFolderId != null) ...[
                const SizedBox(height: 12),
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.blue[50],
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.info_outline,
                        size: 20,
                        color: Colors.blue[700],
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          'This folder will be created inside the selected parent folder',
                          style: TextStyle(
                            fontSize: 12,
                            color: Colors.blue[900],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: _isCreating ? null : () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _isCreating ? null : _createFolder,
          child:
              _isCreating
                  ? const SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                  : const Text('Create'),
        ),
      ],
    );
  }
}
